### ISSUE TITLE
three players in one room

### ISSUE THREAD

**Issue by spirit-q2** [whimsicaldreamer/XandO#3] opened 2017-03-13 21:33 UTC
If three players tries to join to one room all of them will be set to the room in database

**Comment by whimsicaldreamer** [comment] 2017-03-14 03:41
Is it the case before your PR?

**Comment by whimsicaldreamer** [comment] 2017-03-14 08:19
The problem is fixed on this  1749da1. Take a look if that resolves the issue.

**Closed as completed** 2017-03-14 08:28 UTC
